/**
 * A single chat message as it travels across every layer of Hyunwoo Talk:
 * the Touchgym `memo` textarea, the D1 database, the worker API, the web
 * client and the console script.
 *
 * `ciphertext` is an AES-GCM payload (see {@link ./crypto}) — the plaintext is
 * never stored or transmitted by the backend, so the service is end-to-end
 * encrypted with the shared password.
 */
export interface ChatMessage {
  /** Globally unique id, generated by the sender (used for de-duplication). */
  id: string;
  /** User id of the sender. */
  fromId: string;
  /** User id of the recipient. */
  toId: string;
  /** Creation time, unix epoch milliseconds. */
  ts: number;
  /** Base64 AES-GCM payload of the message body (text + emoji). */
  ciphertext: string;
}

/** A decrypted message — produced client-side after decryption succeeds. */
export interface DecryptedMessage extends ChatMessage {
  /** The recovered plaintext, or `null` when decryption failed. */
  text: string | null;
}

/** Web Push subscription, as produced by `PushManager.subscribe()`. */
export interface PushSubscriptionPayload {
  endpoint: string;
  keys: {
    p256dh: string;
    auth: string;
  };
}
